### PR TITLE
Allow an optional /proto identifier in any:all allow rules

### PR DESCRIPTION
**Pull request by exptom**

### CODE REVIEW

**Comment by exptom** [comment]
This relates to issues #41

**Comment by exptom** [comment]
The  PUPPET_GEM_VERSION="~> 2.7" build on travis is failing due to dependencies not installing. Is anyone able to help with that?

**Comment by attachmentgenie** [comment]
i am working on that, i have fixed it for some of my other modules already.

**Comment by igalic** [comment]
would love to know what your solution is, mine so far is crying

**Comment by exptom** [comment]
@igalic commits squashed :)

**Comment by exptom** [comment]
For some reason this is not working correctly even though grep is returning the correct exit status. Will investigate further and re-open PR.

**Comment by attachmentgenie** [comment]
ok , thanks for the heads up.

@igalic just updated the test matrix to test puppet 2.7 have a look at commit https://github.com/attachmentgenie/attachmentgenie-ufw/commit/4fc3c6262f724939296c3ab60f3e0b10d77bb7a1

**Comment by exptom** [comment]
@attachmentgenie ok, i'm really confused now! The latest version on forge (1.4.9) has a very different init.pp manifest to what exists on master currently. The current master (which I branched to add my fix) is what is causing things to break - my change works if I download the tar.gz of 1.4.9 from forge.

**Comment by exptom** [comment]
Just to clarify I get this error:
```
Error: Could not apply complete catalog: Found 1 dependency cycle:
(File[/etc/default/ufw] => File_line[forward policy] => Class[Ufw] => File[/etc/default/ufw])
```
using the current master (with or without my changes) which appears to be caused by some commits made to master in october since the last tag (1.4.9) was released.

**Comment by attachmentgenie** [comment]
@exptom mmm yes current master is working towards a 2.0.0 release. i ll have try to have to cyclical dependency resolved  so that master can accept new working code

**Pull request closed without merging**
